- Sources/SharingGRDB/FetchKey.swift
While GRDB states that it doesn't support Linux, it does successfully build on Linux, so we should do the same.
Also discovered via SPI builds.
> Fix Linux build

- Examples/Reminders/RemindersLists.swift
During the livestream I noticed that the count of reminders in the list view wasn't correct. It's because we are counting _all_ reminders in the list, not just the un-completed ones. So updating the query...
> Correct count for number of reminders in list.

- Examples/Reminders/ReminderForm.swift
- Examples/Reminders/RemindersListForm.swift
Came across this while responding to #13. We are initializing a bunch of `State` values that weren't really necessary. Think this was just an artifact of us being deep in exploring how to use `@SharedReader` in SwiftUI views and we didn't audit it before releasing.
> No need to initialize State directly.

- Package.resolved
- Tests/SharingGRDBTests/IntegrationTests.swift
- Tests/SharingGRDBTests/SharingGRDBTests.swift
Right now we only run these tests in CI with `swift test`, but in Xcode tests fail to compile due to `Task.sleep(for:)`.
> Update tests to compile in Xcode

- Examples/Reminders/ReminderForm.swift
- Examples/Reminders/ReminderRow.swift
- Examples/Reminders/RemindersListDetail.swift
- Examples/Reminders/RemindersListForm.swift
- Examples/Reminders/RemindersLists.swift
- Examples/Reminders/Schema.swift
- Examples/Reminders/SearchReminders.swift
- Examples/SyncUps/App.swift
- Examples/SyncUps/Schema.swift
- Examples/SyncUps/SyncUpDetail.swift
- Examples/SyncUps/SyncUpsList.swift
- Sources/SharingGRDB/Documentation.docc/Articles/PreparingDatabase.md
Using `inMemory` explicitly unfortunately opens you up to preview crashes at the app entry point where it attempts to open a connection to a file, so let's rely on `@Dependency(\.context)` instead.
> Update database prep examples/docs to use dependency context

- Examples/Reminders/ReminderForm.swift
- Examples/Reminders/RemindersListDetail.swift
- SharingGRDB.xcworkspace/xcshareddata/swiftpm/Package.resolved
Because Reminders is all in the view, meaning new `Shared` instances can pop in during body computations, things like animation are a little less stable. This PR doesn't 100% fix things, but it does make things much more reliable.
> Reminders: Animation Fixes

- Sources/SharingGRDB/FetchKey.swift
- Tests/SharingGRDBTests/SharingGRDBTests.swift
A discussion highlighted this omission:
https://github.com/pointfreeco/sharing-grdb/discussions/25
We knew this was needed but it must've slipped through the cracks before release.
> Include database identity in fetch key

- Package.resolved
- Sources/SharingGRDB/Documentation.docc/Articles/ComparisonWithSwiftData.md
- Sources/SharingGRDB/Documentation.docc/Articles/Fetching.md
- Sources/SharingGRDB/Documentation.docc/Extensions/Fetch.md
- Sources/SharingGRDB/Documentation.docc/Extensions/FetchAll.md
- Sources/SharingGRDB/Documentation.docc/Extensions/FetchOne.md
- Sources/SharingGRDB/Documentation.docc/SharingGRDB.md
- Sources/SharingGRDB/FetchKey+SwiftUI.swift
- Sources/SharingGRDB/FetchKey.swift
- Tests/SharingGRDBTests/SharingGRDBTests.swift
It's possible you want to animate a query sometimes but not other times. Technically this will maintain 2 separate observations of the same query when done.
> Include animation identity in fetch key

- Sources/SharingGRDB/Documentation.docc/Articles/PreparingDatabase.md
In all the examples above this, `appDatabase` is a standalone function but in these two places the return type is `Self` not `any DatabaseWriter` as it is as the process is being described.
> Self -> any DatabaseWriter

- README.md
Quick fix to point the readme link to the latest release (0.1.1) docs.
> Update README.md to point to the latest release docs

- Sources/SharingGRDBCore/Documentation.docc/Articles/Fetching.md
- Sources/SharingGRDBCore/FetchAll.swift
- Sources/SharingGRDBCore/FetchOne.swift
- Tests/SharingGRDBTests/SharingGRDBTests.swift
We can now do this:
```swift
@FetchAll(#sql("…")) var results: [Result]
```
…instead of this:
```swift
@FetchAll(#sql("…", as: Result.self)) var results
```
> Improve type-inference for #sql.

- .github/workflows/ci.yml
- Sources/SharingGRDBCore/Fetch.swift
- Sources/SharingGRDBCore/FetchAll.swift
- Sources/SharingGRDBCore/FetchOne.swift
While database observation should automatically refresh things, there are cases when you may want to refresh things manually, like external changes or in tests to avoid a thread hop.
> Surface `@FetchAll.load()`, etc.

- .github/workflows/ci.yml
- Sources/StructuredQueriesGRDBCore/QueryCursor.swift
- Sources/StructuredQueriesGRDBCore/SQLiteQueryDecoder.swift
- Sources/StructuredQueriesGRDBCore/Statement+GRDB.swift
I saw that the linux build failed and wondered if we should rely on the GRDBSQLite module instead of raw SQLite3.
From what I understand, that should resolve to SQLite3 on Darwin, but use libsqlite3 on Linux.
Also, I copied over the Linux pieces from [swift-sharing](https://github.com/pointfreeco/swift-sharing/blob/main/.github/workflows/ci.yml) & added installing sqlite.
Let me know what you think & happy to adjust!
> fix linux build by importing GRDBSQLite

- Examples/Reminders/Schema.swift
- Examples/SyncUps/Schema.swift
- Sources/SharingGRDBCore/Documentation.docc/Articles/PreparingDatabase.md
> Use OSLog in docs and demo schemas

- Examples/Reminders/RemindersListDetail.swift
- Examples/Reminders/Schema.swift
- Examples/Reminders/SearchReminders.swift
- Package.swift
- SharingGRDB.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Sources/StructuredQueriesGRDBCore/Seed.swift
- Tests/SharingGRDBTests/FetchTests.swift
This logic is being incorporated directly into StructuredQueries: https://github.com/pointfreeco/swift-structured-queries/pull/29
> Leverage upstream database seeding helper

- README.md
- Sources/SharingGRDB/Documentation.docc/SharingGRDB.md
We should point out to users that they should generally depend on the `SharingGRDB` module and not worry about the others.
> Better document modules/installation

- Sources/SharingGRDBCore/Fetch.swift
- Sources/SharingGRDBCore/FetchAll.swift
- Sources/SharingGRDBCore/FetchOne.swift
While `load` is the primary API for reloading a key, we should promote this synchronous API, as well.
> Add projected setter to `@Fetch` wrappers

- Sources/StructuredQueriesGRDBCore/QueryCursor.swift
Fixes #57 
Due to a bug in Xcode previews, one cannot use "legacy preview execution" when linking our library. This is happening because we have some `@usableFromInline` internal APIs that Xcode can't see when building for previews, and so gives us errors that those APIs need to be public or marked as `@usableFromInline` (which they are). So, this just makes those APIs public.
> Fix legacy preview execution.

- .github/workflows/ci.yml
- Sources/SharingGRDBCore/FetchAll.swift
- Sources/SharingGRDBCore/FetchKey+SwiftUI.swift
- Sources/SharingGRDBCore/FetchOne.swift
- Sources/SharingGRDBCore/Internal/Deprecations.swift
- Sources/StructuredQueriesGRDBCore/Statement+GRDB.swift
- Tests/SharingGRDBTests/FetchTests.swift
Introduce the following changes:
- `@FetchOne` and `fetchOne` will automatically introduce `LIMIT 1` clauses to select statements.
- `@FetchOne` can now be assigned an _optional_ value for a given statement and fetch the first row or `nil`.
- `@FetchAll` and `@FetchOne` overloads for parameter packs have been deprecated. There are many overloads to maintain to support them, but they are not very ergonomic. We provide a far better tool for packing values together, and that's the `@Selection` macro, so let's steer folks that direction.
> `@FetchOne` improvements

- Sources/SharingGRDBCore/FetchKey.swift
- Tests/SharingGRDBTests/FetchAllTests.swift
- Tests/SharingGRDBTests/FetchTests.swift
- Tests/SharingGRDBTests/IntegrationTests.swift
- Tests/SharingGRDBTests/SharingGRDBTests.swift
Since `@SharedReader` takes care of all synchronization for us, we do not need to incur an additional thread hop with value observation schedulers. This has the added benefit of making tests a lot easier to write since we don't have to wait around for an initial value.
> Use an immediate schedule in FetchKey.

- Package.resolved
- SharingGRDB.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Sources/StructuredQueriesGRDBCore/QueryCursor.swift
- Tests/SharingGRDBTests/FetchAllTests.swift
- Tests/SharingGRDBTests/FetchTests.swift
- Tests/SharingGRDBTests/IntegrationTests.swift
Let's surface more information about which column failed to decode.
> Improve query decoding errors

- Sources/SharingGRDBCore/Fetch.swift
- Sources/SharingGRDBCore/FetchAll.swift
- Sources/SharingGRDBCore/FetchKey+SwiftUI.swift
- Sources/SharingGRDBCore/FetchOne.swift
Apparently `SwiftuI.Animation` was made hashable only in the iOS 17 era, but due to a compiler bug Swift will happily synthesize a conformance to `Hashable` without checking availability restrictions. So, we have to enforce this ourselves.
> Fix hash availability of Animation.

- README.md
- Sources/SharingGRDBCore/Documentation.docc/SharingGRDBCore.md
> swiftdata's sort is order in sharing-grdb

- Examples/CloudKitDemo/CloudKitDemoApp.swift
- Examples/CloudKitPlayground/CloudKitPlaygroundApp.swift
- Examples/CloudKitPlayground/Schema.swift
- Examples/Examples.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Examples/Reminders/RemindersApp.swift
- Examples/Reminders/Schema.swift
- README.md
- Sources/SharingGRDBCore/CloudKit/DefaultSyncEngine.swift
- Sources/SharingGRDBCore/CloudKit/SyncEngine.swift
- Sources/SharingGRDBCore/Documentation.docc/Articles/CloudKit.md
- Sources/SharingGRDBCore/Documentation.docc/Articles/CloudKitSharing.md
- Sources/SharingGRDBCore/Documentation.docc/Articles/ComparisonWithSwiftData.md
- Sources/SharingGRDBCore/Documentation.docc/SharingGRDBCore.md
- Infer default cloud container using SwiftData
- Statically require string identifier primary keyed tables
Before:
```swift
try SyncEngine(
container: CKContainer(
identifier: "iCloud.co.pointfree.Reminders"
),
database: $0.defaultDatabase
tables: [RemindersList.self, Reminder.self]
)
```
After:
```swift
try SyncEngine(
for: $0.defaultDatabase
tables: RemindersList.self, Reminder.self
)
```
Diff:
```diff
try SyncEngine(
-  container: CKContainer(
-    identifier: "iCloud.co.pointfree.Reminders"
-  ),
-  database: $0.defaultDatabase
+  for: $0.defaultDatabase
-  tables: [RemindersList.self, Reminder.self]
+  tables: RemindersList.self, Reminder.self
)
```
> Improve `SyncEngine.init`

- Examples/Examples.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.resolved
- Package.swift
- Sources/SharingGRDBCore/CloudKit/RecordType+MacroExpansion.swift
- Sources/SharingGRDBCore/CloudKit/StateSerialization+MacroExpansion.swift
- Sources/SharingGRDBCore/CloudKit/SyncMetadata+MacroExpansion.swift
- Sources/SharingGRDBCore/CloudKit/SyncMetadata.swift
- Sources/SharingGRDBCore/CloudKit/Triggers.swift
- Sources/SharingGRDBCore/CloudKit/UnsyncedRecordID+MacroExpansion.swift
- Tests/SharingGRDBTests/CloudKitTests/AccountLifecycleTests.swift
- Tests/SharingGRDBTests/CloudKitTests/ReferenceViolationTests.swift
The macros in StructuredQueries has changed a bit so regenerating their code for our CloudKit tables.
> Regenerate macro code for CloudKit tables.

- Examples/Examples.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Examples/Reminders/ReminderForm.swift
- Examples/Reminders/RemindersDetail.swift
- Examples/Reminders/RemindersLists.swift
- Examples/Reminders/Schema.swift
- Examples/Reminders/SearchReminders.swift
- Examples/Reminders/TagRow.swift
- Examples/Reminders/TagsForm.swift
- Package.swift
Based on the discussion in #117 I have updated the reminders demo to show how one can enforce uniqueness of tag titles. This is done by making the title of the tag the primary key and using an "ON UPDATE CASCADE" foreign key so that if one edits a tag title it updates all rows pointing to that tag.
I have also updated the UI to make it possible to create, edit and delete tags.
> Add uniqueness to tag titles.

- Examples/Reminders/ReminderForm.swift
- Sources/SharingGRDBCore/CloudKit/Metadatabase.swift
- Sources/SharingGRDBCore/CloudKit/SyncEngine.swift
- Sources/SharingGRDBCore/CloudKit/SyncMetadata+MacroExpansion.swift
- Sources/SharingGRDBCore/CloudKit/SyncMetadata.swift
- Sources/SharingGRDBCore/CloudKit/Triggers.swift
- Sources/SharingGRDBCore/Documentation.docc/Articles/CloudKitSharing.md
- Tests/SharingGRDBTests/CloudKitTests/CloudKitTests.swift
- Tests/SharingGRDBTests/CloudKitTests/ForeignKeyConstraintTests.swift
- Tests/SharingGRDBTests/CloudKitTests/NewTableSyncTests.swift
- Tests/SharingGRDBTests/CloudKitTests/SharingTests.swift
- Tests/SharingGRDBTests/CloudKitTests/TriggerTests.swift
- Tests/SharingGRDBTests/Internal/BaseCloudKitTests.swift
This PR adds a bunch of improvements to edge cases of sharing:
* When a user deletes a shared record, we now also delete the associated `CKShare`.
* _However_, when the _sharee_ is the one deleting the shared record, we must _only_ delete the `CKShare` and not delete any of the actual records from CloudKit. Doing so causes an error in CloudKit because you have relinquished access to the record and so you are not allowed to delete it or its children records.
* When one creates/writes/deletes a record that is in a shared context (whether it be the root record or an associated record) we reference the share's permissions (if it exists) to see if you are allowed to make edits. If you are not allowed to make edits the database request will fail with a specific error that you can catch if …
> Handling more CloudKit sharing edge cases

- Sources/SharingGRDBCore/CloudKit/CloudContainer.swift
- Sources/SharingGRDBCore/CloudKit/CloudKit+StructuredQueries.swift
- Sources/SharingGRDBCore/CloudKit/CloudKitSharing.swift
- Sources/SharingGRDBCore/CloudKit/Internal/MockCloudContainer.swift
- Sources/SharingGRDBCore/CloudKit/Internal/MockCloudDatabase.swift
- Sources/SharingGRDBCore/CloudKit/Internal/MockSyncEngine.swift
- Sources/SharingGRDBCore/CloudKit/SyncEngine.swift
- Sources/SharingGRDBCore/CloudKit/SyncEngineProtocol.swift
- Tests/SharingGRDBTests/CloudKitTests/MockCloudDatabaseTests.swift
- Tests/SharingGRDBTests/CloudKitTests/SharingTests.swift
Right now we have a huge blind spot in testing when it comes to how the sync engine deals with sharing. This PR makes things a bit more testable.
> Making sharing more testable

- Package.swift
- Package@swift-6.0.swift
- Sources/SharingGRDBCore/CloudKit/SyncEngine.swift
- Sources/SharingGRDBCore/Internal/DataManager.swift
- Sources/SharingGRDBCore/Internal/UserDatabase.swift
- Tests/SharingGRDBTests/CloudKitTests/AccountLifecycleTests.swift
- Tests/SharingGRDBTests/CloudKitTests/CloudKitTests.swift
- Tests/SharingGRDBTests/CloudKitTests/FetchRecordZoneChangesTests.swift
- Tests/SharingGRDBTests/CloudKitTests/FetchedDatabaseChangesTests.swift
- Tests/SharingGRDBTests/CloudKitTests/ForeignKeyConstraintTests.swift
- Tests/SharingGRDBTests/CloudKitTests/MergeConflictTests.swift
- Tests/SharingGRDBTests/CloudKitTests/MetadataTests.swift
- Tests/SharingGRDBTests/CloudKitTests/MockCloudDatabaseTests.swift
- Tests/SharingGRDBTests/CloudKitTests/NewTableSyncTests.swift
- Tests/SharingGRDBTests/CloudKitTests/NextRecordZoneChangeBatchTests.swift
- Tests/SharingGRDBTests/CloudKitTests/RecordTypeTests.swift
- Tests/SharingGRDBTests/CloudKitTests/SyncEngineLifecycleTests.swift
- Tests/SharingGRDBTests/CloudKitTests/SyncEngineTests.swift
- Tests/SharingGRDBTests/CloudKitTests/SyncEngineValidationTests.swift
- Tests/SharingGRDBTests/CloudKitTests/UserlandTests.swift
- Tests/SharingGRDBTests/Internal/BaseCloudKitTests.swift
- Tests/SharingGRDBTests/Internal/CloudKit+CustomDump.swift
- Tests/SharingGRDBTests/Internal/CloudKitTestHelpers.swift
- Tests/SharingGRDBTests/Internal/Schema.swift
- Tests/SharingGRDBTests/Internal/UserDatabaseHelpers.swift
- Tests/SharingGRDBTests/SharingGRDBTests.swift
Should hopefully get us closer to green CI.
> CloudKit: Compile tests on non-macOS platforms

- Examples/Examples.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Examples/Reminders/Helpers.swift
- Package.resolved
- Package.swift
Just a minor change to the Reminders demo, which defined a custom query representation.
> StructuredQueries 0.16 support

- Sources/SharingGRDBCore/CloudKit/Triggers.swift
- Sources/SharingGRDBCore/Internal/UserDatabase.swift
- Tests/SharingGRDBTests/CloudKitTests/AccountLifecycleTests.swift
- Tests/SharingGRDBTests/CloudKitTests/AssetsTests.swift
- Tests/SharingGRDBTests/CloudKitTests/CloudKitTests.swift
- Tests/SharingGRDBTests/CloudKitTests/FetchRecordZoneChangesTests.swift
- Tests/SharingGRDBTests/CloudKitTests/FetchedDatabaseChangesTests.swift
- Tests/SharingGRDBTests/CloudKitTests/ForeignKeyConstraintTests.swift
- Tests/SharingGRDBTests/CloudKitTests/MergeConflictTests.swift
- Tests/SharingGRDBTests/CloudKitTests/MetadataTests.swift
- Tests/SharingGRDBTests/CloudKitTests/MockCloudDatabaseTests.swift
- Tests/SharingGRDBTests/CloudKitTests/NewTableSyncTests.swift
- Tests/SharingGRDBTests/CloudKitTests/NextRecordZoneChangeBatchTests.swift
- Tests/SharingGRDBTests/CloudKitTests/ReferenceViolationTests.swift
- Tests/SharingGRDBTests/CloudKitTests/SharingPermissionsTests.swift
- Tests/SharingGRDBTests/CloudKitTests/SharingTests.swift
- Tests/SharingGRDBTests/CloudKitTests/SyncEngineLifecycleTests.swift
- Tests/SharingGRDBTests/CloudKitTests/TriggerTests.swift
- Tests/SharingGRDBTests/Internal/BaseCloudKitTests.swift
If we detect that someone has changed the primary key of a row (which should be rare, but can happen), we need to be sure to delete the record in CloudKit with the old primary key.
> Delete CK record when updating primary key.

- Sources/SharingGRDBCore/CloudKit/CloudKitSharing.swift
- Sources/SharingGRDBCore/CloudKit/SyncEngine.swift
- Sources/SharingGRDBCore/Documentation.docc/Articles/CloudKit.md
- Sources/SharingGRDBCore/Documentation.docc/Articles/CloudKitSharing.md
- Sources/SharingGRDBCore/Internal/Exports.swift
- Tests/SharingGRDBTests/CloudKitTests/SharingPermissionsTests.swift
- Tests/SharingGRDBTests/CloudKitTests/SyncEngineValidationTests.swift
Updated a bunch of docs and along the way made a few fixes/improvements:
* We now enforce that uniqueness constraints cannot be used on non-primary key tables. I think we have no choice but to enforce this.
* I removed the only place we use `@Dependency(\.defaultSyncEngine)` within the library which makes it possible for people to run multiple sync engines if they want.
> Lots of updates to docs.

- Makefile
- Sources/SQLiteData/CloudKit/IdentifierStringConvertible.swift
- Sources/SQLiteData/CloudKit/Internal/Triggers.swift
- Sources/SQLiteData/Documentation.docc/Articles/CloudKit.md
- Sources/SQLiteData/Documentation.docc/Articles/CloudKitSharing.md
- Sources/SQLiteData/Documentation.docc/Extensions/Database.md
- Sources/SQLiteData/Documentation.docc/Extensions/IdentifierStringConvertible.md
- Sources/SQLiteData/Documentation.docc/Extensions/SystemFieldsRepresentation.md
- Sources/SQLiteData/Documentation.docc/SQLiteData.md
> CloudKit docs organization

- Examples/Reminders/Schema.swift
- Examples/SyncUps/Schema.swift
- Sources/SQLiteData/Documentation.docc/Articles/PreparingDatabase.md
- Sources/SQLiteData/Documentation.docc/SQLiteData.md
- Sources/SQLiteData/StructuredQueries+GRDB/DefaultDatabase.swift
This small helper will take live/test/preview into account to simplify how folks bootstrap their databases.
> Add `database` for context-sensitive provisioning

- Package.resolved
- Package.swift
- Package@swift-6.0.swift
- Sources/SQLiteData/CloudKit/Internal/CloudKitFunctions.swift
- Sources/SQLiteData/CloudKit/Internal/Triggers.swift
- Sources/SQLiteData/CloudKit/SyncEngine.swift
- Sources/SQLiteData/CloudKit/SyncMetadata.swift
- Tests/SQLiteDataTests/CloudKitTests/NextRecordZoneChangeBatchTests.swift
- Tests/SQLiteDataTests/CloudKitTests/SharingTests.swift
- Tests/SQLiteDataTests/CloudKitTests/SyncEngineLifecycleTests.swift
- Tests/SQLiteDataTests/CloudKitTests/TriggerTests.swift
We don't currently support moving a record from one zone to another (e.g. moving a reminder out of a shared list and into a private list, or vice-versa). We would like to support it eventually, but for now when we detect this situation we will throw an error.
> Throw error when changing zones for existing record
